# Generated by Django 5.0.2 on 2024-03-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_name_alter_comment_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('bio', models.TextField()),
                ('linkedin_url', models.URLField(default='', max_length=105)),
                ('location', models.CharField(blank=True, default='', max_length=30)),
                ('birth_date', models.DateField(blank=True, default='', null=True)),
                ('phone', models.IntegerField(blank=True, default='', null=True)),
                ('github', models.URLField(default='', max_length=256)),
                ('occupation', models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Software Engineering', 'Software Engineering'), ('ML Engineer', 'ML Engineer'), ('Ethical Hacker', 'Ethical Hacker'), ('Blockchain', 'Blockchain'), ('Cryptography', 'Cryptography')], default='', max_length=256)),
                ('website_url', models.URLField(default='', max_length=256)),
                ('instagram_url', models.URLField(default='', max_length=256)),
                ('facebook_url', models.URLField(default='', max_length=256)),
                ('twitter_url', models.URLField(default='', max_length=256)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
