# Generated by Django 5.0.2 on 2024-03-15 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Software Engineering', 'Software Engineering'), ('ML Engineer', 'ML Engineer'), ('Ethical Hacker', 'Ethical Hacker'), ('Blockchain', 'Blockchain'), ('Cryptography', 'Cryptography')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(default='', max_length=105),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='bg.jpg', null=True, upload_to='images/'),
        ),
    ]
